import struct

TYPE_REQUEST_APPEND_ENTRY =  0x50
TYPE_RESPONSE_APPEND_ENTRY = 0x51
TYPE_REQUEST_VOTE = 0x60
TYPE_RESPONSE_VOTE = 0x61

TYPE_DATAGRAM_FRAGMENT = 0xF0


LEN_TYPE_FIELD = 1
LEN_TERM = 1
LEN_SERVER_ID = 16
LEN_LOG_INDEX = 8
LEN_BOOL = 1
LEN_DATA_LENGTH = 1



LEN_HEARTBEAT_APPENDENTRY_PACKET = (LEN_TYPE_FIELD + LEN_TERM 
                    + LEN_SERVER_ID + LEN_LOG_INDEX + LEN_TERM + LEN_LOG_INDEX + LEN_DATA_LENGTH)


LEN_REQUEST_VOTE_PACKET = (LEN_TYPE_FIELD + LEN_TERM 
                    + LEN_SERVER_ID + LEN_LOG_INDEX + LEN_LOG_INDEX)

LEN_RESPONSE_VOTE_PACKET =  (LEN_TYPE_FIELD + LEN_TERM + LEN_BOOL)




